"""Add meter_type and remove requires_meter

Revision ID: 0f4a48c3c8d3
Revises: 76bc9d219f67
Create Date: 2026-03-06 15:26:59.927234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4a48c3c8d3'
down_revision: Union[str, Sequence[str], None] = '76bc9d219f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Column already added in previous failed run
    # op.add_column('data_elements', sa.Column('meter_type', sa.String(length=50), nullable=True))
    with op.batch_alter_table('profiling_questions', schema=None) as batch_op:
        batch_op.drop_column('requires_meter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiling_questions', sa.Column('requires_meter', sa.BOOLEAN(), nullable=True))
    op.drop_column('data_elements', 'meter_type')
    # ### end Alembic commands ###
