"""update_admin_models_v3

Revision ID: 420c36d11686
Revises: bef3f7a45449
Create Date: 2026-03-17 19:29:12.895141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import app.models.company

# revision identifiers, used by Alembic.
revision: str = '420c36d11686'
down_revision: Union[str, Sequence[str], None] = 'bef3f7a45449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_audit_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('changes')

    with op.batch_alter_table('data_submissions', schema=None) as batch_op:
        batch_op.alter_column('evidence_files',
               existing_type=sa.TEXT(),
               type_=app.models.company.JSONEncodedDict(),
               existing_nullable=True)

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=20), nullable=True))
        batch_op.alter_column('framework_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_frameworks_framework_id'), ['framework_id'], unique=True)

    with op.batch_alter_table('meter_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('profiling_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiling_questions', schema=None) as batch_op:
        batch_op.drop_column('is_required')
        batch_op.drop_column('input_type')

    with op.batch_alter_table('meter_types', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('unit')

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frameworks_framework_id'))
        batch_op.alter_column('framework_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('version')
        batch_op.drop_column('region')

    with op.batch_alter_table('data_submissions', schema=None) as batch_op:
        batch_op.alter_column('evidence_files',
               existing_type=app.models.company.JSONEncodedDict(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('_alembic_tmp_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
