"""add_trial_expires_at

Revision ID: 75c4f90c87b2
Revises: a89fa218f4b5
Create Date: 2026-06-16 06:05:23.635004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c4f90c87b2'
down_revision: Union[str, Sequence[str], None] = 'a89fa218f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('company_checklists', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_company_checklists_users', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('data_elements', schema=None) as batch_op:
        batch_op.alter_column('condition_logic',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('frameworks',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('meter_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.alter_column('framework_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('profiling_questions', schema=None) as batch_op:
        batch_op.alter_column('frameworks',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiling_questions', schema=None) as batch_op:
        batch_op.alter_column('frameworks',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('frameworks', schema=None) as batch_op:
        batch_op.alter_column('framework_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('data_elements', schema=None) as batch_op:
        batch_op.alter_column('meter_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('frameworks',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('condition_logic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('company_checklists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_checklists_users', type_='foreignkey')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('trial_expires_at')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
