"""Add is_developer to User

Revision ID: 76bc9d219f67
Revises: 841fd7e5933b
Create Date: 2026-03-05 22:49:44.343626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bc9d219f67'
down_revision: Union[str, Sequence[str], None] = '841fd7e5933b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_developer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_developer')
    # ### end Alembic commands ###
