"""add ai_dashboard_items table

Revision ID: ac95cd9a2f12
Revises: 75c4f90c87b2
Create Date: 2026-08-23 10:24:48.083031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.company


# revision identifiers, used by Alembic.
revision: str = 'ac95cd9a2f12'
down_revision: Union[str, Sequence[str], None] = '75c4f90c87b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_dashboard_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chart', app.models.company.JSONEncodedDict(), nullable=False),
    sa.Column('source_question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_dashboard_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_dashboard_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_dashboard_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_dashboard_items_id'))

    op.drop_table('ai_dashboard_items')
    # ### end Alembic commands ###
