"""add audit_logs composite index for ai chat quota

Revision ID: ae848b9a0509
Revises: ac95cd9a2f12
Create Date: 2026-08-27 10:03:23.593417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae848b9a0509'
down_revision: Union[str, Sequence[str], None] = 'ac95cd9a2f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_company_action_created', ['company_id', 'action', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_company_action_created')

    # ### end Alembic commands ###
